# vim: set ft=dockerfile:

FROM ubuntu:xenial

# Colour output.
ENV TERM=xterm

RUN apt-get update -y \
    && apt-get install -y apt-transport-https software-properties-common \
    && apt-get --no-install-recommends install -y \
      curl \
      python3 \
      python3-dev \
      python3-pip \
      coreutils \
      net-tools \
    # && curl https://bootstrap.pypa.io/get-pip.py | python3 \
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
