---
# Required for Java 1.8
- name: Configure Additional Repositories for Debian/Ubuntu
  block:
    - name: install buster-backports repository
      apt_repository:
        repo: deb http://security.debian.org/debian-security stretch/updates main
      when: ansible_distribution_release == 'buster'
      register: buster_backports

    - name: install trusty-openjdk repository
      apt_repository:
        repo: ppa:openjdk-r/ppa
      when: ansible_distribution_release == 'trusty'
      register: trusty_backports

    - name: Update Cache (Apt)
      apt:
        update_cache: yes
      when: buster_backports.changed or trusty_backports.changed
  when: ansible_os_family == 'Debian'

- name: install Minecraft dependencies
  apt:
    name: "{{ dependencies }}"
    state: present
    install_recommends: no

# 2021-03-15
# At this time, Forge will not load with any JDK version above 1.8
- name: Install Alternate JDK
  block:
    - name: Install Java JDK8
      apt:
        name: openjdk-8-jdk
        state: present
        install_recommends: no

    - name: correct java version on trusty
      alternatives:
        name: java
        path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  when: ansible_distribution_release == 'trusty' or minecraft_server == 'forge'

- name: install Spigot dependencies
  apt:
    name: ['git', 'tar']
  when: minecraft_server == 'spigot'
