---
- name: include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: include Debian-specific tasks
  include_tasks: setup/Debian.yml
  when: ansible_os_family == 'Debian'

- name: include Red Hat-specific tasks
  include_tasks: setup/RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: create Minecraft group
  group:
    state: present
    name: "{{ minecraft_group }}"
    system: yes

- name: create Minecraft user
  user:
    state: present
    name: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    home: "{{ minecraft_home }}"

- name: set executable name (Minecraft)
  set_fact:
    minecraft_jar: minecraft_server.jar
  when: minecraft_server == 'minecraft'

- name: set executable name (Spigot)
  set_fact:
    minecraft_jar: spigot.jar
  when: minecraft_server == 'spigot'

- name: set executable name (Forge)
  set_fact:
    minecraft_jar: forge.jar
  when: minecraft_server == 'forge'

# 2021-02-06
# Using systemd with Ubuntu 18.04 is not supported. Use Supervisor instead
- name: Check if Ubuntu and set process_control_version
  set_fact:
    minecraft_process_control: supervisor
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version > '16.04'

- debug:
    var: minecraft_process_control

- name: Include Supervisor tasks
  include_tasks: setup/supervisor.yml
  when: minecraft_process_control == 'supervisor'

- name: Include Systemd tasks
  include_tasks: setup/systemd.yml
  when: minecraft_process_control == 'systemd'
