---
- name: install Minecraft dependencies
  yum:
    name: "{{ dependencies }}"
    state: present

- name: install Spigot dependencies
  yum:
    name: ['git', 'tar']
  when: minecraft_server == 'spigot'
