---
- name: symlink Minecraft server
  file:
    src: "{{ minecraft_home }}/minecraft_server.{{ minecraft_version_latest | default(minecraft_version) }}.jar"
    path: "{{ minecraft_home }}/minecraft_server.jar"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: link
  register: symlink_created
  notify:
    - restart Minecraft

- name: Update Ownership of Symlink
  shell: "chown -h {{ minecraft_user }}:{{ minecraft_group}} {{ minecraft_home }}/minecraft_server.jar"
  args:
    warn: false
  when: symlink_created.changed

- name: agree to EULA
  copy:
    src: eula.txt
    dest: "{{ minecraft_home }}/eula.txt"
    mode: '0644'
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify:
    - enable service
