---
# The only way to generate a server.properties file is to start Minecraft.
# We send the stop command to the stdin to stop the server right after it
# starts.

# => 2019-07-06
# => TODO: We have to skip the test 306 for Ansible lint due to the need to pass
# => the 'stop' command here when generating the server.properties file.  I was
# => unable to get the args:stdin to properly pass in the call so I added this
# => stop gap.
- name: generate server.properties
  shell: echo "stop" | java -jar {{ minecraft_jar }} nogui  # noqa 306
  args:
    creates: server.properties
    chdir: "{{ minecraft_home }}"
  become: yes
  become_user: "{{ minecraft_user }}"

- name: update server.properties
  minecraft_server_file:
    server_file: server-properties
    values: "{{ minecraft_server_properties }}"
    path: "{{ minecraft_home }}/server.properties"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
  notify:
    - restart Minecraft
