---
- name: check for supported OS
  assert:
    that:
      - "ansible_os_family in supported_ansible_os_families"

- name: check for supported server implementation
  assert:
    that:
      - "minecraft_server in supported_minecraft_servers"

- name: Minecraft before setup hook
  include_tasks: "{{ minecraft_hook_before_setup | default('empty.yml') }}"

- name: Minecraft Install Pre-requisites
  include_tasks: setup/main.yml

- name: Minecraft after setup hook
  include_tasks: "{{ minecraft_hook_after_setup | default('empty.yml') }}"

- name: Minecraft before download hook
  include_tasks: "{{ minecraft_hook_before_download | default('empty.yml') }}"

- name: Minecraft Download Media
  include_tasks: download/main.yml

- name: Minecraft after download hook
  include_tasks: "{{ minecraft_hook_after_download | default('empty.yml') }}"

- name: Minecraft before install hook
  include_tasks: "{{ minecraft_hook_before_install | default('empty.yml') }}"

- name: Minecraft Install Media
  include_tasks: install/main.yml

- name: Minecraft after install hook
  include_tasks: "{{ minecraft_hook_after_install | default('empty.yml') }}"

- name: Minecraft Configure ACL
  include_tasks: acl.yml

- name: Minecraft Configure Server Properties
  include_tasks: configure.yml

- name: Minecraft before start hook
  include_tasks: "{{ minecraft_hook_before_start | default('empty.yml') }}"

- name: Install Mod Packs
  include_tasks: install-mods.yml
  when: include_mods

- meta: flush_handlers

- name: Minecraft after start hook
  include_tasks: "{{ minecraft_hook_after_start | default('empty.yml') }}"
