---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: minecraft_default
    image: minecraft_xenial64:python2
    pull: false
    privileged: True
    command: /sbin/init
scenario:
  name: default
  test_sequence:
    - lint
    - syntax
    - destroy
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: True
verifier:
  name: testinfra
  lint:
    name: flake8
