# vim: set ft=dockerfile:

FROM debian:buster

# Colour output.
ENV TERM=xterm

RUN apt-get update -y \
    && apt-get install -y apt-transport-https software-properties-common \
    && apt-get --no-install-recommends install -y \
      curl \
      python \
      python-dev \
      python-pip \
      coreutils \
      net-tools \
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
