# vim: set ft=dockerfile:

FROM debian:stretch

# Colour output.
ENV TERM=xterm

RUN apt-get update -y \
    && apt-get install -y apt-transport-https software-properties-common \
    && apt-get --no-install-recommends install -y \
      curl \
      python3 \
      python3-dev \
      python3-pip \
      coreutils \
      net-tools \
    && apt-get autoremove \
    && apt-get clean \
    && ln -snf /lib/systemd/systemd /sbin/init \
    && rm -rf /var/lib/apt/lists/*
