---
- name: Create Ansible Temporary Directory
  file:
    path: "{{ minecraft_tmp_directory }}"
    state: directory
    mode: 0755

- name: Retrieve Versions Manifest
  get_url:
    url: "{{ minecraft_version_manifest_url }}"
    dest: "{{ minecraft_tmp_directory }}/versions_manifest.json"

- name: Load Versions Manifest
  set_fact:
    minecraft_versions: "{{ (lookup('file', {{ minecraft_tmp_directory }}/versions_manifest.json)).stdout | from_json).versions  }}"

- name: find latest release version
  set_fact:
    minecraft_version: "{{ (minecraft_versions.stdout | from_json).latest.release }}"
  when: minecraft_version == "latest"

- name: use the configured minecraft version number
  set_fact:
    minecraft_version: "{{ minecraft_version }}"
  when: minecraft_version != "latest"

- name: extract version specific mainfest file
  set_fact:
    minecraft_version_manifest_url: "{{ minecraft_versions | selectattr('id','match', (minecraft_version|string) ) | map(attribute='url')  | list | first }}"

- name: Retrieve Versions Manifest
  get_url:
    url: "{{ minecraft_version_manifest_url }}"
    dest: "{{ minecraft_tmp_directory }}/versions_manifest.json"

- name: Load Versions Manifest
  set_fact:
    minecraft_version_info: "{{ lookup('file', {{ minecraft_tmp_directory }}/versions_manifest.json) }}"

- name: "extract the download url from version manifest"
  set_fact:
    minecraft_server_download_url: "{{ ( minecraft_version_info.stdout | from_json).downloads.server.url }}"
    minecraft_server_download_checksum: "sha1:{{ (minecraft_version_info.stdout | from_json).downloads.server.sha1 }}"
