---
- include_tasks: minecraft.yml
  when: minecraft_server == 'minecraft'

- include_tasks: spigot.yml
  when: minecraft_server == 'spigot'

- include_tasks: forge.yml
  when: minecraft_server == 'forge'
